### ISSUE TITLE
Memory requirements for the API?

### ISSUE THREAD

**Issue by vshahrda** [cdsframework/ice#31]
Hello, I have set up an instance of the openCDS calculation machine on one of our VMs. The machine has 2GB of memory and I have set the `km.threads=3`.

While doing some testing with a sample patient input with around 20 immunization records in the payload, we encounter the below error:

```
java.lang.OutOfMemoryError: Java heap space
```

What is the minimum system/memory requirements for this service? I have already configured Tomcat9 to increase the memory, but still getting this error:
```
set CATALINA_OPTS=-Xms4096m -Xmx4096m;
set JAVA_OPTS="-Xms4096m -Xmx4096m"
```

**Comment by op-kevin-graveley** [comment]
Documentation has the the memory settings at: -Xms512m -Xmx2560m

I'm running on a 1g container for testing.
If your VM has 2GB of ram maybe try -Xms512m -Xmx1024m

**Comment by vshahrda** [comment]
After some investigation, we discovered that the request had some duplicate records that was causing the memory spike. Closing this. Thanks for the response.
