### ISSUE TITLE
ICE Announcement Subscription Link gives 403

### ISSUE THREAD

**Issue by nscott** [cdsframework/ice#43]
https://groups.google.com/a/hln.com/forum/#!forum/ice-announcements is not public, so there's no way to join.

**Comment by darylbc** [comment]
Thanks for letting us know. We'll take a look. In the meantime, if you'd like to be added to the ICE announcements list, please e-mail us at ice@hln.com with the e-mail address that you'd like added.

**Comment by darylbc** [comment]
Subscription link has been replaced with a [web form](https://docs.google.com/forms/d/e/1FAIpQLSeeeOLj7arRnJUl4vBtJZsCDKOcP-76vlL0PP-KduGglxJdWQ/viewform).
