### ISSUE TITLE
source of truth for group codes?

### ISSUE THREAD

**Issue by horner** [cdsframework/ice#48]
@darylbc 

The only place I have found for mapping CVX codes to group codes is in the files in https://github.com/cdsframework/ice/tree/master/ice3/opencds-ice-service/src/main/resources/knowledgeModule/gov.nyc.cir.ice/ice-supporting-data/Series

For example:
https://github.com/cdsframework/ice/blob/9f53897801715feb40f15cb90b22ec90fa872627/ice3/opencds-ice-service/src/main/resources/knowledgeModule/gov.nyc.cir.ice/ice-supporting-data/Series/COVID19AstraZenecaSeries.xml#L16

Is there a better place to get the mapping of CVX codes to group codes/names?

**Comment by darylbc** [comment]
@horner - The mappings are also in the [ICE Implementation Guide](https://bitbucket.org/cdsframework/ice/downloads/ICE-Implementation-Guide-distrib.pdf), starting on page 59.

The ICE codes are also maintained in a [Google Sheet](https://docs.google.com/spreadsheets/d/1JB8QN2QeJACJmGdSkCaHr6LQ_8T942-J65Fjf_JDpic/edit). The mappings are currently not maintained here, but we could add a worksheet with those mappings if it would be helpful.
